### ISSUE TITLE
undefined: util.LogPrint

### ISSUE THREAD

**Issue by mehdirahmati** [casbin/session-role-manager#2]
i get this error when compile program

**Comment by hsluoyz** [comment]
@nodece @GopherJ @kingiw @dovics can anyone fix it?

**Comment by dovics** [comment]
@hsluoyz I create a pr, please review

**Comment by hsluoyz** [comment]
@MehdiRahmati please use v2.0.0: https://github.com/casbin/session-role-manager/releases
